In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [26]:
from sklearn.datasets import load_iris
iris = load_iris()

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size= 0.2)

In [28]:
from sklearn.linear_model import LogisticRegression

In [29]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

1.0

In [30]:
from sklearn.svm import SVC

In [31]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9666666666666667

In [32]:
from sklearn.ensemble import RandomForestClassifier

In [33]:
rm = RandomForestClassifier()
rm.fit(X_train,y_train)
rm.score(X_test,y_test)

1.0

In [34]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [35]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [36]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9666666666666667

In [37]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [38]:
# scores_l = []
# scores_svm = []
# scores_rf = []

# for train_index,test_index in kf.split(iris.data):
#     X_train,X_test,y_train,y_test = iris.data[train_index],iris.data[test_index], \
#                                     iris.target[train_index],iris.target[test_index]
#     scores_l.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
#     scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
#     scores_rf.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))

In [39]:
# SVC(X_train,y_train)

In [40]:
from sklearn.model_selection import cross_val_score

In [41]:
cross_val_score(LogisticRegression(),iris.data,iris.target)

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [42]:
cross_val_score(SVC(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [43]:
cross_val_score(RandomForestClassifier(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [44]:
cross_val_score(RandomForestClassifier(n_estimators=40),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [45]:
cross_val_score(RandomForestClassifier(n_estimators=15),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [46]:
# cross_val_score(RandomForestClassifier(n_estimators=18880),iris.data,iris.target)

In [47]:
cross_val_score(RandomForestClassifier(n_estimators=100),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [48]:
cross_val_score(RandomForestClassifier(n_estimators=250),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])